//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constellation.Sitecore.Links
{
    
    
    /// <summary>
    /// The SharedContent Configuration Section.
    /// </summary>
    public partial class SharedContent : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the SharedContent Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SharedContentSectionName = "sharedContent";
        
        /// <summary>
        /// Gets the SharedContent instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::Constellation.Sitecore.Links.SharedContent Instance
        {
            get
            {
                return ((global::Constellation.Sitecore.Links.SharedContent)(global::System.Configuration.ConfigurationManager.GetSection(global::Constellation.Sitecore.Links.SharedContent.SharedContentSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContent.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContent.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region SharedContentFolders Property
        /// <summary>
        /// The XML name of the <see cref="SharedContentFolders"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SharedContentFoldersPropertyName = "sharedContentFolders";
        
        /// <summary>
        /// Gets or sets the SharedContentFolders.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The SharedContentFolders.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContent.SharedContentFoldersPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=true)]
        public virtual global::Constellation.Sitecore.Links.SharedContentFolders SharedContentFolders
        {
            get
            {
                return ((global::Constellation.Sitecore.Links.SharedContentFolders)(base[global::Constellation.Sitecore.Links.SharedContent.SharedContentFoldersPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContent.SharedContentFoldersPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Constellation.Sitecore.Links
{
    
    
    /// <summary>
    /// A collection of SharedContentFolder instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Constellation.Sitecore.Links.SharedContentFolder), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Constellation.Sitecore.Links.SharedContentFolders.SharedContentFolderPropertyName)]
    public partial class SharedContentFolders : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SharedContentFolderPropertyName = "sharedContentFolder";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Constellation.Sitecore.Links.SharedContentFolders.SharedContentFolderPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Constellation.Sitecore.Links.SharedContentFolders.SharedContentFolderPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Constellation.Sitecore.Links.SharedContentFolder)(element)).TemplateName;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Constellation.Sitecore.Links.SharedContentFolder();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.Links.SharedContentFolder this[int index]
        {
            get
            {
                return ((global::Constellation.Sitecore.Links.SharedContentFolder)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> with the specified key.
        /// </summary>
        /// <param name="templateName">The key of the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.Links.SharedContentFolder this[object templateName]
        {
            get
            {
                return ((global::Constellation.Sitecore.Links.SharedContentFolder)(base.BaseGet(templateName)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="sharedContentFolder">The <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Constellation.Sitecore.Links.SharedContentFolder sharedContentFolder)
        {
            base.BaseAdd(sharedContentFolder);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="sharedContentFolder">The <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Constellation.Sitecore.Links.SharedContentFolder sharedContentFolder)
        {
            base.BaseRemove(this.GetElementKey(sharedContentFolder));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.Links.SharedContentFolder GetItemAt(int index)
        {
            return ((global::Constellation.Sitecore.Links.SharedContentFolder)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> with the specified key.
        /// </summary>
        /// <param name="templateName">The key of the <see cref="global::Constellation.Sitecore.Links.SharedContentFolder"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.Links.SharedContentFolder GetItemByKey(string templateName)
        {
            return ((global::Constellation.Sitecore.Links.SharedContentFolder)(base.BaseGet(((object)(templateName)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Constellation.Sitecore.Links
{
    
    
    /// <summary>
    /// The SharedContentFolder Configuration Element.
    /// </summary>
    public partial class SharedContentFolder : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region TemplateName Property
        /// <summary>
        /// The XML name of the <see cref="TemplateName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string TemplateNamePropertyName = "templateName";
        
        /// <summary>
        /// Gets or sets the TemplateName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The TemplateName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.TemplateNamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string TemplateName
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContentFolder.TemplateNamePropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.TemplateNamePropertyName] = value;
            }
        }
        #endregion
        
        #region RootPath Property
        /// <summary>
        /// The XML name of the <see cref="RootPath"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string RootPathPropertyName = "rootPath";
        
        /// <summary>
        /// Gets or sets the RootPath.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The RootPath.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.RootPathPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string RootPath
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContentFolder.RootPathPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.RootPathPropertyName] = value;
            }
        }
        #endregion
        
        #region ParentPageQuery Property
        /// <summary>
        /// The XML name of the <see cref="ParentPageQuery"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ParentPageQueryPropertyName = "parentPageQuery";
        
        /// <summary>
        /// Gets or sets the ParentPageQuery.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ParentPageQuery.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.ParentPageQueryPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string ParentPageQuery
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContentFolder.ParentPageQueryPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.ParentPageQueryPropertyName] = value;
            }
        }
        #endregion
        
        #region CategorizedBySiteFolder Property
        /// <summary>
        /// The XML name of the <see cref="CategorizedBySiteFolder"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string CategorizedBySiteFolderPropertyName = "categorizedBySiteFolder";
        
        /// <summary>
        /// Gets or sets the CategorizedBySiteFolder.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The CategorizedBySiteFolder.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.CategorizedBySiteFolderPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool CategorizedBySiteFolder
        {
            get
            {
                return ((bool)(base[global::Constellation.Sitecore.Links.SharedContentFolder.CategorizedBySiteFolderPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.CategorizedBySiteFolderPropertyName] = value;
            }
        }
        #endregion
        
        #region PathToSiteFolder Property
        /// <summary>
        /// The XML name of the <see cref="PathToSiteFolder"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string PathToSiteFolderPropertyName = "pathToSiteFolder";
        
        /// <summary>
        /// Gets or sets the PathToSiteFolder.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The PathToSiteFolder.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.PathToSiteFolderPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string PathToSiteFolder
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContentFolder.PathToSiteFolderPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.PathToSiteFolderPropertyName] = value;
            }
        }
        #endregion
        
        #region FolderName Property
        /// <summary>
        /// The XML name of the <see cref="FolderName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string FolderNamePropertyName = "folderName";
        
        /// <summary>
        /// Gets or sets the FolderName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The FolderName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SharedContentFolder.FolderNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string FolderName
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SharedContentFolder.FolderNamePropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SharedContentFolder.FolderNamePropertyName] = value;
            }
        }
        #endregion
    }
}
