//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constellation.Sitecore.Links
{
    
    
    /// <summary>
    /// The SwitchingLinkProviderConfiguration Configuration Section.
    /// </summary>
    public partial class SwitchingLinkProviderConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the SwitchingLinkProviderConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SwitchingLinkProviderConfigurationSectionName = "switchingLinkProvider";
        
        /// <summary>
        /// Gets the SwitchingLinkProviderConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration Instance
        {
            get
            {
                return ((global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.SwitchingLinkProviderConfigurationSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region DefaultLinkProviderType Property
        /// <summary>
        /// The XML name of the <see cref="DefaultLinkProviderType"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DefaultLinkProviderTypePropertyName = "defaultLinkProviderType";
        
        /// <summary>
        /// Gets or sets the DefaultLinkProviderType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The DefaultLinkProviderType.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.DefaultLinkProviderTypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::System.Type DefaultLinkProviderType
        {
            get
            {
                return ((global::System.Type)(base[global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.DefaultLinkProviderTypePropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.DefaultLinkProviderTypePropertyName] = value;
            }
        }
        #endregion
        
        #region LinkProviderRules Property
        /// <summary>
        /// The XML name of the <see cref="LinkProviderRules"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LinkProviderRulesPropertyName = "linkProviderRules";
        
        /// <summary>
        /// Gets or sets the LinkProviderRules.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LinkProviderRules.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.LinkProviderRulesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Constellation.Sitecore.LinkProviderRules LinkProviderRules
        {
            get
            {
                return ((global::Constellation.Sitecore.LinkProviderRules)(base[global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.LinkProviderRulesPropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.Links.SwitchingLinkProviderConfiguration.LinkProviderRulesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Constellation.Sitecore
{
    
    
    /// <summary>
    /// A collection of LinkProviderRule instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Constellation.Sitecore.LinkProviderRule), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Constellation.Sitecore.LinkProviderRules.LinkProviderRulePropertyName)]
    public partial class LinkProviderRules : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Constellation.Sitecore.LinkProviderRule"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LinkProviderRulePropertyName = "linkProviderRule";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Constellation.Sitecore.LinkProviderRules.LinkProviderRulePropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Constellation.Sitecore.LinkProviderRules.LinkProviderRulePropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Constellation.Sitecore.LinkProviderRule)(element)).Site;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Constellation.Sitecore.LinkProviderRule"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Constellation.Sitecore.LinkProviderRule"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Constellation.Sitecore.LinkProviderRule();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.LinkProviderRule this[int index]
        {
            get
            {
                return ((global::Constellation.Sitecore.LinkProviderRule)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> with the specified key.
        /// </summary>
        /// <param name="site">The key of the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.LinkProviderRule this[object site]
        {
            get
            {
                return ((global::Constellation.Sitecore.LinkProviderRule)(base.BaseGet(site)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="linkProviderRule">The <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Constellation.Sitecore.LinkProviderRule linkProviderRule)
        {
            base.BaseAdd(linkProviderRule);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Constellation.Sitecore.LinkProviderRule"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="linkProviderRule">The <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Constellation.Sitecore.LinkProviderRule linkProviderRule)
        {
            base.BaseRemove(this.GetElementKey(linkProviderRule));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.LinkProviderRule GetItemAt(int index)
        {
            return ((global::Constellation.Sitecore.LinkProviderRule)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> with the specified key.
        /// </summary>
        /// <param name="site">The key of the <see cref="global::Constellation.Sitecore.LinkProviderRule"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Constellation.Sitecore.LinkProviderRule GetItemByKey(string site)
        {
            return ((global::Constellation.Sitecore.LinkProviderRule)(base.BaseGet(((object)(site)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Constellation.Sitecore
{
    
    
    /// <summary>
    /// The LinkProviderRule Configuration Element.
    /// </summary>
    public partial class LinkProviderRule : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Site Property
        /// <summary>
        /// The XML name of the <see cref="Site"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SitePropertyName = "site";
        
        /// <summary>
        /// Gets or sets the Site.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Site.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.LinkProviderRule.SitePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Site
        {
            get
            {
                return ((string)(base[global::Constellation.Sitecore.LinkProviderRule.SitePropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.LinkProviderRule.SitePropertyName] = value;
            }
        }
        #endregion
        
        #region LinkProviderType Property
        /// <summary>
        /// The XML name of the <see cref="LinkProviderType"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LinkProviderTypePropertyName = "linkProviderType";
        
        /// <summary>
        /// Gets or sets the LinkProviderType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LinkProviderType.")]
        [global::System.ComponentModel.TypeConverter(typeof(global::System.Configuration.TypeNameConverter))]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Constellation.Sitecore.LinkProviderRule.LinkProviderTypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::System.Type LinkProviderType
        {
            get
            {
                return ((global::System.Type)(base[global::Constellation.Sitecore.LinkProviderRule.LinkProviderTypePropertyName]));
            }
            set
            {
                base[global::Constellation.Sitecore.LinkProviderRule.LinkProviderTypePropertyName] = value;
            }
        }
        #endregion
    }
}
